version: "3.8"

services:
  moviebrowser-backend:
    build: .
    container_name: moviebrowser-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the database directory to persist data
      - ./database_instance:/app/database_instance
      # Mount the data directory for seeders
      - ./data:/app/data
      # Mount F: drive for video uploads and access (WSL path)
      - /mnt/f:/app/videos
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
